### ISSUE TITLE
[error] Unknown File Format

### ISSUE THREAD

**Issue by jj2neat** [LolWastedJS/discord.js-andesite#1]
Ive downloaded the latest JAR-all file (the link you provided in docs) I keep getting this exception for some reason

[17:28:16] [lava-daemon-pool-info-loader-2-thread-1/ERROR] [RestHandler]: Error in HTTP handler
java.util.concurrent.CompletionException: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unknown file format.
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
        at andesite.node.handler.RequestHandler$1.loadFailed(RequestHandler.java:383)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:240)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:226)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unknown file format.
        at com.sedmelluq.discord.lavaplayer.source.ProbingAudioSourceManager.handleLoadResult(ProbingAudioSourceManager.java:35)
        at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:82)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218)
        ... 4 common frames omitted

**Comment by viztea** [comment]
You provided an unknown file format when loading tracks. Also, I recommend switching to lavalink as andesite-node has been archived by the developer.

You can use my lavalink client: https://github.com/lavaclient/lavaclient, it has a similar api.
